### ISSUE TITLE
Production use

### ISSUE THREAD

**Issue by kteza1** [Covertness/coap-rs#1]
Hi. Thank you very much for this crate. Is this ready for production use?

**Comment by Covertness** [comment]
Most features about the CoAP has been implemented. If you don't care about [cache](https://tools.ietf.org/html/rfc7252#section-5.6) or [DTLS](https://tools.ietf.org/html/rfc7252#section-9), I think you could use it in production.These features will be added in the future.

**Comment by kteza1** [comment]
Thanks
