### ISSUE TITLE
Support DTLS encryption

### ISSUE THREAD

**Issue by tiziano88** [Covertness/coap-rs#16]
Some products (e.g. IKEA Tradfri) use COAP over DTLS (TLS over UDP). It would be great to have the library support this use case.

See
- https://learn.pimoroni.com/tutorial/sandyj/controlling-ikea-tradfri-lights-from-your-pi
- https://tools.ietf.org/html/rfc6347
- https://docs.rs/openssl/0.9.19/openssl/ssl/struct.SslMethod.html#method.dtls

**Comment by tiziano88** [comment]
Also https://docs.rs/openssl/0.9.19/openssl/ssl/struct.SslMethod.html#method.dtls

**Comment by Covertness** [comment]
Thank you for your advice. I have [the similar idea](https://github.com/Covertness/coap-rs/issues/1#issuecomment-165116666) before. Unfortunately, I haven't enough time to implement this feature.
Of cource , any PR about the feature are welcome.

**Comment by Covertness** [comment]
DTLS written in Rust seems not available. I found two issues about this:
https://github.com/ctz/rustls/issues/40
https://github.com/sfackler/rust-openssl/issues/528
Waiting for the implement.

**Comment by StEvUgnIn** [comment]
I thought Core CoAP Standard included DTLS 1.0/1.2 .

**Comment by StEvUgnIn** [comment]
I found this code based on tokio-openssl which includes DTLS encryption:
https://github.com/simmons/tokio-dtls-example/blob/master/src/main.rs

**Comment by StEvUgnIn** [comment]
I started working on the implementation based on the latter example. I would like @Covertness to assign this issue to me before I present my PR.

**Comment by StEvUgnIn** [comment]
I am working on now after a family member of mine had health issue. Have you tried this project? https://github.com/google/rust-async-coap

**Comment by Covertness** [comment]
I noticed it before. It seems only implement some basic functions and haven't contribute for a long time

**Comment by fdeantoni** [comment]
Hi guys! Has anybody been able to make progress on this? I looked at this a couple of years ago implementing DTLS with rust-async-coap (see [async-coap-dtls](https://github.com/fdeantoni/async-coap-dtls)) but my very crude attempt is quite clunky. [DTLS 1.3](https://datatracker.ietf.org/doc/draft-ietf-tls-dtls13/) should make things a lot simpler but this is still a draft if I'm not mistaken...

**Comment by Covertness** [comment]
I think it's not easy to implement. I would appreciate if you could finish it.

**Comment by StEvUgnIn** [comment]
@fdeantoni 
Feel free to continue if you are interested.
