### ISSUE TITLE
Building for Linux

### ISSUE THREAD

**Issue by tl8roy** [Covertness/coap-rs#20]
I am looking at building this for Linux however I am getting the following error:
```
error: failed to build archive: Text file busy

error: aborting due to previous error

error: Could not compile `winapi-build`.
```

This is using the minimal example provided.

**Comment by Covertness** [comment]
Could you give more info? It seems like some files are using by other process.

**Comment by tl8roy** [comment]
Sorry, was on the way out and decided to just through it up.

I was using a Linux VM on a Windows box. The files were in a shared folder and it was built on the windows box before hand.

I have used this VM to compile stuff before, so I know that the process should work.

No other build processes are running at the same time.

I might copy the files to a native directory and see if that works.

**Comment by tl8roy** [comment]
I tried building from a native directory. That seemed to work. I guess that solves the issue, but makes it a PITA.

**Comment by Covertness** [comment]
Closed. Reopen it if you meet any new problem about it.
