### ISSUE TITLE
Issues with IPv6 address in URLs

### ISSUE THREAD

**Issue by curio77** [Covertness/coap-rs#24]
`coap-rs` depends on an ancient version of `rust-url` (v0.2.36 of Jul 2015) that appears to have issues with IPv6 addresses in URLs.  Upgrading this dependency needs to take care of API changes, however. (Sadly, I'm too much of a Rust noob still to do this myself and offer a PR.)

Anyway, the effect is that `coap-rs` will choke on URLs such as `"coap://[bbbb::9329:f033:f558:7418]/.well-known/core"` with a "domain error".

**Comment by curio77** [comment]
Well, having looked into this a little further, I'm not sure that the IPv6 issues are `rust-url`'s fault. Rather, in parsing the given URL, `coap-rs` attempts to obtain a domain (presumably implying a reverse-lookup if a host address is given) where IMO the literal host should be considered (stripped of the encapsulating brackets in the case of an IPv6 URL). I'll work on a pull request resolving the issue this way...

**Comment by Covertness** [comment]
I will update the version of `rust-url`

**Comment by curio77** [comment]
Not strictly necessary, I think, as IPv6 addresses now work thanks to the PR, but on the other hand, being up-to-date is always good. :-)
