### ISSUE TITLE
Communication with the IKEA-tradfri gateway

### ISSUE THREAD

**Issue by henriktorget** [Covertness/coap-rs#27]
Very happy to se coap implemented in rust.
 
I am trying to communicate with my IKEA tradfri gateway over the coap-protocol. 
The request i am trying to do is to mimic this terminal command:

`coap-client -m post -u "Client_identity" -k "$GATEWAYCODE" -e '{"9090":"$USERNAME"}' "coaps://$GATEWAYIP:5684/15011/9063"`

My understanding from reading https://github.com/obgm/libcoap/:

-e is the payload
-k is supposed to add a key to the header
-u is adding a user to the header

But when i try to use the example_post() code in the gateway does not even respond with a status code.

As you can see in the terminal command above the request is to 'coaps:://' and not 'coap::// which im thinking might be where my problem lies. I have not managed to find where this is set in the source of coap-rs.

In addition to this i cant seem to find the best way to mimic adding a key or user to the header from looking at the source of coap-rs.

Anybody that could enlighten me? Would be much appreciated.

**Comment by henriktorget** [comment]
Ahaa, i did not make the connection between TDLS and the 's' in coaps.
I can look around and se if it has been implemented somewhere else.

**Comment by Covertness** [comment]
I still looking for the rust implementation. You can follow #16 . Close this one.
