### ISSUE TITLE
Async client requests

### ISSUE THREAD

**Issue by weili-jiang** [Covertness/coap-rs#29]
It appears that the underlying IO library is asynchronous, and the server implementation does indeed expose an asynchronous handler interface.

It would be nice if the client side could also be made to have an asynchronous interface rather than having to do a blocking read.

**Comment by Covertness** [comment]
Can you tell me what would you do with the async client request ? I think the blocking request is enough for most clients

**Comment by weili-jiang** [comment]
It would be to free up the main thread to perform other asynchronous IO. I realise that this can also be done externally by wrapping it with something like a futures pool (or simply a worker thread pool)...

**Comment by Covertness** [comment]
https://github.com/Covertness/coap-rs/pull/88
