### ISSUE TITLE
Document way for clients to send non-GET requests

### ISSUE THREAD

**Issue by chrysn** [Covertness/coap-rs#36]
It appears that the only way to construct a client request without manually splitting the URI (ie. re-implementing parse_coap_url) is using the `get` method, which precludes the use of different request methods.

Please document how a request POST or PUT message, with possible additional options, is supposed to be created from a URI.

**Comment by Covertness** [comment]
Thank you for your advice. Now you can find the examples in https://github.com/Covertness/coap-rs/tree/master/examples
