### ISSUE TITLE
Receive multicast messages on wpan0 with IPv6 address

### ISSUE THREAD

**Issue by vervaekejonathan** [Covertness/coap-rs#46]
Hi,
I'm trying to receive multicast coap messages from a thread network.
This network is available via wpan0 and has ipv6 addresses.
I'm trying the server demo, with the following modification:
`let addr = ":::0";`
Unfortunately, I do not receive any packages.
What could be wrong?

Things I've tried:
- set address to 0.0.0.0:5683 and send packages via ipv4 on eth0 -> this works fine
- receive the multicast messages with a node.js implementation -> this works fine

Thanks.

**Comment by Covertness** [comment]
It seems the addr format should be `[::1]:5683` . The IPv6 should be supported by #24 .

**Comment by vervaekejonathan** [comment]
Unfortunately, that does not fix the problem. (It does work when send a coap message from the device that also runs the rust server. )

Could it have to do with using the broadcast address (i'm sending to ff03::1) or with receiving on wpan0 instead of eth0? Is there a way to debug this? A lowlevel function with raw packages or something?

**Comment by Covertness** [comment]
Yes. Just noticed you are want to receive the multicast messages. The Multicast has specified addresses by https://www.iana.org/assignments/ipv6-multicast-addresses/ipv6-multicast-addresses.xhtml . You can check the messages by some network diagnose tools like Wireshark

**Comment by Covertness** [comment]
Closed. Reopen it if you meet any problem about it.

**Comment by vervaekejonathan** [comment]
Solved by using `[::]:5683` Thanks!
