### ISSUE TITLE
Unexpected panic due to network connectivity state

### ISSUE THREAD

**Issue by xanium4332** [Covertness/coap-rs#77]
https://github.com/Covertness/coap-rs/blob/76bea972df92f0b730d24435921b9a86b95d42c3/src/client.rs#L175

The referenced `unwrap()` causes a panic based on the current network connectivity situation of the host. This is an external situation w.r.t. to the line in question (not a programmer error) and so an `Result::Err(_)` should be raised instead.

**Comment by Covertness** [comment]
Thanks. Fixed.
