### ISSUE TITLE
Outdated documentation refrenced

### ISSUE THREAD

**Issue by chrysn** [Covertness/coap-rs#78]
The crate metadata reference the documentation stored on http://covertness.github.io/coap-rs/master/coap/index.html. That doesn't tell its exact version, but quick bisection shows it's at a roughly February 2020 state.

Please either continue updating that documentation, or just change the link to the automatically built documentation at https://docs.rs/coap/.

**Comment by Covertness** [comment]
Fixed. Thank you for pointing out. The link will be updated in the next version.
