### ISSUE TITLE
Blockwise transfer for with a request payload

### ISSUE THREAD

**Issue by digitwolf** [Covertness/coap-rs#82]
Are there any plans / ideas / thoughts around implementation of Blockwise transfer for Block1 type of requests?
I can help with the implementation.

https://datatracker.ietf.org/doc/html/rfc7959#section-2.5

**Comment by Covertness** [comment]
Do you mean the client post the block1 payload ? The Block1 has been implemented on server side.

**Comment by digitwolf** [comment]
Well yeah I was expecting that if a client is trying to send a large payload then it would use Blockwise transfer to send it. But it's just failing.

**Comment by Covertness** [comment]
Sorry forgot to implement this part. It will be awesome if you can help.

**Comment by Covertness** [comment]
fixed in #85
