### ISSUE TITLE
Server response retransmission due to duplicate client request (duplicate MID)

### ISSUE THREAD

**Issue by elrafoon** [Covertness/coap-rs#84]
Hello,

I have a case when remote modem-connected client does not hear response to its latest request, so it retransmits the request, with the same MID.

I thought this is handled in coap-rs library server code, but it seems it's not.

What's the usual solution to this - when request with the same MID is received from the same endpoint?
Should my (user) code on server side just re-execute the request handler again producing new response, or should it cache previous response and just resend the response?

I need clarification on this.

Thanks.

**Comment by elrafoon** [comment]
Thank you for info.

**Comment by Covertness** [comment]
Closed. Reopen it if you have any new problem about it.
