### ISSUE TITLE
0.12.2's update of coap-lite is incompatible

### ISSUE THREAD

**Issue by chrysn** [Covertness/coap-rs#87]
The 0.12.2 version updated the coap-lite dependency from 0.9 to 0.11. That update is semver incompatible because some coap APIs (eg. post_with_timeout) implicitly re-export coap-lite types.

The only semver compatible way out of this is yanking the 0.12.2 version, and re-publish as 0.13.0. Otherwise, acknowledging that this happened and will not be yanked is also fine with me (most dependencies that are affected can probably work around it by depending on ^0.12.2 and coap-lite 0.11) -- in which case I'd just like to ask for more careful re-exporting in future updates.

**Comment by Covertness** [comment]
Thanks for your prompt feedback
