### ISSUE TITLE
Mio 1.8.8 incompatible with newer Tokio versions

### ISSUE THREAD

**Issue by Snowda** [Covertness/coap-rs#92]
Versions of Tokio >=1.34 and higher require Mio >=1.8.9 and causes a version conflict when compiling as coap uses 1.8.8.

A semver bump may resolve this unless there are other aspects that this introduces that would need testing first?

**Comment by Covertness** [comment]
I think it's no big deal because the difference in version numbers is not very big. You can have a try.

**Comment by osobiehl** [comment]
I think we can even just remove `mio` as a dependency now. we do not use it directly
